In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [181]:
w1 = np.random.randn(2, 2)
w2 = np.random.randn(2, )

sigmoid = lambda x: 1/(1 + np.exp(-x))
d_sigmoid = lambda x: x * (1-x)

In [182]:
train_input = np.array([
    [0, 0], [1, 1],
    [0, 1], [1, 0]
])
train_output = np.array([0, 0, 1, 1])

In [183]:
w1

array([[-1.94177385, -0.37063028],
       [-0.55419141, -0.67250652]])

In [184]:
w2

array([-1.33456132,  0.27773478])

In [185]:
b = sigmoid(np.dot(train_input[3], w1))
print(b)

c = sigmoid(np.dot(b, w2))
print(c)

[0.12545311 0.40838873]
0.486503001395108


In [211]:
w1 = np.random.randn(2, 2)
w2 = np.random.randn(2, )

In [206]:
lr = 0.1

In [203]:
for i in range(10_000):
    for i in range(4):
        x = train_input[i]
        y = train_output[i]
        
        b = sigmoid(np.dot(x, w1))
        c = sigmoid(np.dot(b, w2))
        e2 = 2*(c - y) * d_sigmoid(c)
        dw2 = b * e2
        
        e1 = e2*w2 * d_sigmoid(b)
        dw1 = np.array([
            [x[0] * e1[0], x[0] * e1[1]],
            [x[1] * e1[0], x[1] * e1[1]],
        ])
        w1 = w1 - lr * dw1
        w2 = w2 - lr * dw2

In [215]:
for i in range(4):
    b = sigmoid(np.dot(w1, train_input[i]))
    c = sigmoid(np.dot(w2, b))
    print(train_output[i])
    print(c)
    print()

0
0.005129786386451751

0
2.6608065589922203e-05

1
0.0005464869548777376

1
2.6640738180095618e-05



In [214]:
for i in range(10_000):
    l_dw1 = []
    l_dw2 = []
    for i in range(4):
        x = train_input[i]
        y = train_output[i]

        b = sigmoid(np.dot(x, w1))
        c = sigmoid(np.dot(b, w2))
        e2 = 2*(c - y) * d_sigmoid(c)
        dw2 = b * e2

        e1 = e2*w2 * d_sigmoid(b)
        dw1 = np.array([
            [x[0] * e1[0], x[0] * e1[1]],
            [x[1] * e1[0], x[1] * e1[1]],
        ])
        l_dw1.append(dw1)
        l_dw2.append(dw2)
    w1 = w1 - lr * sum(l_dw1)
    w2 = w2 - lr * sum(l_dw2)

In [175]:
w2

array([-0.057587  , -7.86518344])

In [177]:
e1

array([4.25268506e-06, 1.56265838e-04])

In [178]:
x

array([1, 0])

In [180]:
np.dot(x, e1)

4.252685062118434e-06

In [122]:
x

array([1, 0])

In [149]:
np.dot(x, e1)

-0.07846739789068655

In [25]:
dz2 = a2-y
dw2 = np.dot(dz2,a1.T)/m
dz1 = np.dot(w2.T,dz2) * a1*(1-a1)
dw1 = np.dot(dz1,x.T)/m

dw1 = np.reshape(dw1,w1.shape)
dw2 = np.reshape(dw2,w2.shape)    
return dz2,dw2,dz1,dw1

NameError: name 'a2' is not defined

In [26]:
i = 1
x = train_input[i]
y = train_output[i]
b = np.dot(w1, x)
c = np.dot(w2, b)
print(b)
print(c)

[1.38081456 0.14810406]
0.9869927908721081


In [62]:
b * e2

array([-0.21668702, -0.20967998])

In [33]:
e2 = (c - y) * c * (1 - c)
e2

0.012671034806353561

In [32]:
np.dot(e2, b)

array([1.36285401, 0.14617764])

In [114]:
dw2 = np.dot(b, e2)

w2 = w2 - lr * dw2
e1 = np.dot(w2.T, e2)
dw1 = np.dot(e1, x.T) * (x * (1 - x))
w1 = w1 - lr * dw1

ValueError: shapes (2,) and (1,) not aligned: 2 (dim 0) != 1 (dim 0)

In [111]:
np.dot(np.linalg.inv(w1), w1)

array([[ 1.00000000e+00,  5.46467176e-17],
       [-8.77043830e-17,  1.00000000e+00]])

In [108]:
w1

array([[0.33885386, 0.41713258],
       [0.35749447, 0.25511746]])

In [109]:
w1.T

array([[0.33885386, 0.35749447],
       [0.41713258, 0.25511746]])

In [110]:
np.linalg.inv(w1) 

array([[-4.07047845,  6.65548015],
       [ 5.70393547, -5.40651874]])

In [59]:
b.T

array([0.43981084, 0.41199513])

In [113]:
b

array([0.75598643, 0.61261192])