https://youtu.be/kft1AJ9WVDk

In [2]:
import numpy as np

In [3]:
sigmoid = lambda x: 1/(1 + np.exp(-x))
d_sigmoid = lambda x: x * (1-x)

In [4]:
train_input = np.array([
    [0, 0],
    [1, 1],
    [1, 0],
    [0, 1]
])
train_input

array([[0, 0],
       [1, 1],
       [1, 0],
       [0, 1]])

In [5]:
train_output = np.array([[0, 1, 1, 0]]).T
train_output

array([[0],
       [1],
       [1],
       [0]])

In [6]:
synaptic_weigths = 2*np.random.random((2, 1)) -1
synaptic_weigths

array([[ 0.60434485],
       [-0.5026226 ]])

In [7]:
input_layer = train_input
output = sigmoid(np.dot(input_layer, synaptic_weigths))
output

array([[0.5       ],
       [0.52540866],
       [0.64664971],
       [0.37692455]])

In [8]:
for epoch in range(1000):
    input_layer = train_input
    output = sigmoid(np.dot(input_layer, synaptic_weigths))
    error = train_output - output
    ajustement = error * d_sigmoid(output)
    
    synaptic_weigths += np.dot(input_layer.T, ajustement)
output

array([[0.5       ],
       [0.96639677],
       [0.99850104],
       [0.04138663]])

In [11]:
input_layer.T

array([[0, 1, 1, 0],
       [0, 1, 0, 1]])

In [10]:
import sys
sys.version

'3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]'