In [1]:
import numpy as np

In [4]:
a = np.random.random((4, 5)) 
a

array([[0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224],
       [0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184],
       [0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761],
       [0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116]])

In [31]:
np.append(a.T,  np.ones((1, 4)).T).T

array([0.27584278, 0.72607017, 0.73572853, 0.84533984, 0.89407253,
       0.16198519, 0.73752088, 0.94466054, 0.85947789, 0.50956387,
       0.14800815, 0.69016385, 0.41981094, 0.489129  , 0.30986053,
       0.99868974, 0.73347224, 0.30892184, 0.66918761, 0.86444116,
       1.        , 1.        , 1.        , 1.        ])

In [9]:
 np.ones((1, 5)).T

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [38]:
np.concatenate((a,a))

array([[0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224],
       [0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184],
       [0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761],
       [0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116],
       [0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224],
       [0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184],
       [0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761],
       [0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116]])

In [35]:
a

array([[0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224],
       [0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184],
       [0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761],
       [0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116]])

In [36]:
np.concatenate(a)

array([0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224,
       0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184,
       0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761,
       0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116])

In [37]:
a

array([[0.27584278, 0.89407253, 0.85947789, 0.41981094, 0.73347224],
       [0.72607017, 0.16198519, 0.50956387, 0.489129  , 0.30892184],
       [0.73572853, 0.73752088, 0.14800815, 0.30986053, 0.66918761],
       [0.84533984, 0.94466054, 0.69016385, 0.99868974, 0.86444116]])