In [1]:
import numpy as np

In [42]:
a = np.random.random((4, 2)) 
a

array([[0.15482118, 0.154069  ],
       [0.83504171, 0.62983271],
       [0.0389719 , 0.26985236],
       [0.09348044, 0.28809063]])

In [31]:
np.append(a.T,  np.ones((1, 4)).T).T

array([0.27584278, 0.72607017, 0.73572853, 0.84533984, 0.89407253,
       0.16198519, 0.73752088, 0.94466054, 0.85947789, 0.50956387,
       0.14800815, 0.69016385, 0.41981094, 0.489129  , 0.30986053,
       0.99868974, 0.73347224, 0.30892184, 0.66918761, 0.86444116,
       1.        , 1.        , 1.        , 1.        ])

In [9]:
 np.ones((1, 5)).T

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [48]:
np.concatenate((a, np.ones((4, 1))), axis=1)[:, :-1]

array([[0.15482118, 0.154069  ],
       [0.83504171, 0.62983271],
       [0.0389719 , 0.26985236],
       [0.09348044, 0.28809063]])

In [49]:
a.shape

(4, 2)

In [50]:
np.ones((4, 1)).shape

(4, 1)