In [9]:
import numpy as np 
from scipy.special import softmax
import tensorflow as tf

In [30]:
a = np.random.random(5) 
a

array([0.46999241, 0.97815501, 0.41967877, 0.42957938, 0.00691736])

In [33]:
def softmax_(x):
    y = np.exp(x)
    axe = max(1, len(a.shape)-1) # calcul le softmax sur l'axe en fonction de la taille 
    somme = np.sum(y, axis=axe)
    y /= somme
    return y

In [44]:
softmax(a)

array([0.19220038, 0.31948204, 0.18276932, 0.18458784, 0.12096042])

In [8]:
a = 3

In [9]:
b = a if a != None else 2

In [1]:
from math import log2

In [4]:
import numpy as np

In [27]:
# example of calculating cross entropy
from math import log2

# calculate cross entropy


H(P, Q): 2.279 bits
H(Q, P): 2.014 bits


In [28]:
cce = tf.keras.losses.CategoricalCrossentropy()

labels_scce = [[0, 1, 2]]
labels_cce  = [[1,    0,  0]]
preds       = [[.90,.05,.05]]

loss_cce  = cce(labels_cce,   preds)
loss_cce

<tf.Tensor: shape=(), dtype=float32, numpy=0.105360545>

In [31]:
def cross_entropy(p, q):
    return -sum([p[i]*np.log(q[i]) for i in range(len(p))])


cross_entropy(labels_cce, preds)

array([ 0.10536052, -0.        , -0.        ])

In [36]:
def cross_entropy(p, q):
    p = np.array(p)
    q = np.array(q)
    return -(p*np.log(q)).sum()

cross_entropy(labels_cce, preds)

0.10536051565782628

In [23]:
np.log(2.718)

0.999896315728952